### ISSUE TITLE
Optimize the Permutations generator

### ISSUE THREAD

**Issue by drupol** [alphazygma/Combinatorics#1]
Hi Alejandro,

Do you think it would be possible to improve the Permutations generator using yield ?
Instead of generating the whole array of solutions, it would take less memory by stopping after "yielding" the value in the generator.

Here's a code example, unfortunately, it doesn't take in account the order of elements and thus, it's not a proper permutation generator => unusable here.

```php
  /**
   * Generate the permutations
   *
   * @return \Generator
   */
  public function generateIgnoreOrder(array $original, $length) {
    $originalLength  = count($original);
    if ($length > $originalLength) {
      $length = $originalLength;
    }
    $remainingLength = $originalLength - $length + 1;

    for ($i = 0; $i < $remainingLength; $i++) {
      $current = $original[$i];
      if ($length === 1) {
        yield [$current];
      } else {
        $remaining = array_slice($original, $i + 1);
        foreach ($this->generate($remaining, $length - 1) as $permutation) {
          array_unshift($permutation, $current);
          yield $permutation;
        }
      }
    }
  }
```

**Comment by alphazygma** [comment]
I spent some time tonight researching the yield functionality and Generators, and found the following.
A) We would need to bump the minimum requirement to PHP 5.5, as Generators were introduced here (so, we may need a side branch for this)
B) I need to spend some more time with generators to figure out the order, the internals of the original source code depend on values generated to be able to create the unique groups, so without having these groups it is a bit harder to create them on the fly. (So definitely requires some more thought)

**Comment by drupol** [comment]
Hi,

Yes it's a tough task, I'm on it since a couple of days actually :-)

I will post a more complete "in-depth" analysis today if I have time, explaining what I did so far.

See you later!

**Comment by drupol** [comment]
In the meantime, you can have a look at what I'm trying to do here: https://github.com/drupol/phpermutations

As you can see, the Combinations class is an iterator, the Permutation is not yet.

I'm trying to convert that Permutation class into an iterator.
